version: '3.7'

services:
  backend:
    # image: goldenprofile_backend
    build: ./server/
    volumes:
      - ./server:/app # As long as flask is started with `debug=True` it's possible to hot-reload
    environment:
      FLASK_ENV: development # TODO: Remove for production
    ports:
      - 8080:8080

  frontend:
    # image: goldenprofile_frontend
    build: ./frontend/
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    environment:
      BACKEND_SVC: backend
    ports:
      - 80:80
      # - 443:443
